### ISSUE TITLE
Clicking on pointer has no effect in safari browser

### ISSUE THREAD

**Issue by 1u** [bozdoz/wp-plugin-leaflet-map#156]
Hi! For your information:
I got reported that the modal doesn't open when clicking on a pointer on the map when using safari (v.15.3)
I can't test it myself. No safari here atm.

https://zuerich-lernt.ch/schenken/

This dialogue doesn't appear:
![image](https://user-images.githubusercontent.com/4281072/159808808-45d08304-5e43-4dfc-a391-6456ec9a8390.png)

Thx a lot for the nice plugin!

**Comment by juuso-turunen** [comment]
Hello!

This could be related to this issue: https://github.com/Leaflet/Leaflet/issues/7255.

It's an issue in Leaflet.js JS library used by this plugin. This issue should be fixed in Leaflet.js version 1.8.0. It's now in beta.

You can try it out by changing this setting in the plugin settings.

![image](https://user-images.githubusercontent.com/44379448/161637200-de397961-2b4c-444e-a980-912dd685270e.png)
JavaScript URL: https://unpkg.com/leaflet@1.8.0-beta.1/dist/leaflet.js


Hopefully this helps! :)

**Comment by 1u** [comment]
Hey, 
Yes probably that's it. Thx a lot for the hint! And the solution proposal.
Now I need an apple to test it :)

**Comment by juuso-turunen** [comment]
You're welcome :)

I don't have any Apple devices either so I can't test it for you. But I hope you find an Apple and solution! 🍎

**Comment by 1u** [comment]
:ok_hand:  A friend could test it and it works now. 
thx again.

Btw: Feel free to use screenshots of the linked web page to describe/promote this nice wp plugin.

**Comment by juuso-turunen** [comment]
Great to hear that!
When the stable version of 1.8.0 come out I recommend that you change to it. Betas have always its own risks :)

P.S. I'm not this plugin developer. I'm just a happy Leaflet user who uses this plugin and loves it!
