### ISSUE TITLE
Gesture Handling

### ISSUE THREAD

**Issue by acadian-nomad** [bozdoz/wp-plugin-leaflet-map#67]
Would it be possible to implement gesture handling functionality into Leaflet Map like this Gesture Handling Leaflet plugin?

Plugin:
https://github.com/elmarquis/Leaflet.GestureHandling

Demo:
https://elmarquis.github.io/Leaflet.GestureHandling/examples/

Thanks!

**Comment by bozdoz** [comment]
I was planning to work on an event feature which would allow adding plugins, though this is a little different than I thought because it's only an option as opposed to a map method.  I suppose I could add a wp filter on the map options, so you could add your own options in functions.php.

I could pass this PHP array to be filtered:

https://github.com/bozdoz/wp-plugin-leaflet-map/blob/master/shortcodes/class.map-shortcode.php#L112

Something like:

```php
$more_options = apply_filters('leaflet-map-options-filter', $more_options);
```

Then you could append to them using add_filter:

```php
function example_callback( $example ) {
    $example['gestureHandling'] = true;
    return $example;
}
add_filter( 'leaflet-map-options-filter', 'example_callback' );
```

using apply_filters: https://developer.wordpress.org/reference/functions/apply_filters/

**Comment by bozdoz** [comment]
Related to #64

**Comment by bozdoz** [comment]
Actually this can be resolved by using the current FAQ of [how to add a plugin](https://github.com/bozdoz/wp-plugin-leaflet-map#how-can-i-add-another-leaflet-plugin).  With the gesture handling script, all you need is: `map.gestureHandling.enable()`

**Comment by hupe13** [comment]
Hi Bozdoz,
I think, you can close this issue, [Extensions for Leaflet Map](https://wordpress.org/support/plugin/extensions-leaflet-map/) handles this.
