### ISSUE TITLE
Leaflet version

### ISSUE THREAD

**Issue by bodograumann** [bozdoz/wp-plugin-leaflet-map#83]
I noticed that an old version of leaflet was loaded.
Turns out this is because, the version is stored in the configuration.
Maybe the default should be changed to `leaflet@latest`?

**Comment by bozdoz** [comment]
I like the idea, and anyone can change their version to `latest` manually.  I'm just not sure if I want to default it to latest, since someone might never change it, and Leaflet could have breaking changes, say in v2.0 someday. Seems safer just to update it semi-regularly.  Especially since minor versions aren't that important.  Thanks! :)

**Comment by bodograumann** [comment]
What about using a semver range in npm-style; E.g. `leaflet@^1.4`? This would select the latest version after `1.4.0` and before `2.0.0`.

Is there a specific reason, why you don’t include leaflet in the plugin?

**Comment by bozdoz** [comment]
I suppose I could do something like a semver, or more easily include leaflet in the plugin.  I didn't include it because it seemed better to use the cdn.  I didn't want to have to manage versions at all.  Ultimately, I still think it's not an important issue.  There are options to specify js and css urls (which could be local, and which could be any version).  I made the plugin when leaflet was at version 0.5 or 0.7, and v1 was a breaking change.  Hope that helps.

**Comment by bodograumann** [comment]
I guess you are right, that this is not really important.
I was just worried that the issues I am experiencing might be related to an outdated version of leaflet.
They are not, so I’m fine with leaving this as it is.
